extends Node2D

const DAMAGE = 10

var start_position : Vector2
var end_position: Vector2
var a: float
var b: float
var c: float
var duration: float
var cumulative_time: float
@onready var exploded = false
@onready var dynamite = $RigidBody2D
@onready var explosion = $explosion
@onready var explosion_collision = $explosion/CollisionShape2D
@onready var explosion_sprite = $explosion/AnimatedSprite2D

func _ready() -> void:
	if not (start_position and end_position):
		queue_free()
	
	# random perturbation
	end_position.x += randf_range(-100, 100)
	end_position.y += randf_range(-50, 50)
	
	explosion.global_position = end_position
		
	# calculate duration based on start and end positions
	duration = (end_position - start_position).length() / 400
	duration = max(duration, 0.7)
	duration = min(duration, 1.5)
	cumulative_time = 0
	
	var middle_point : Vector2
	middle_point.x = (start_position.x + end_position.x) / 2
	middle_point.y = (start_position.y + end_position.y) / 2 - 200
	
	
	var coefficients = find_quadratic_equation([start_position, middle_point, end_position])
	
	if not coefficients:
		queue_free()
	
	a = coefficients["a"]
	b = coefficients["b"]
	c = coefficients["c"]


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	if exploded:
		return
	if cumulative_time > duration and not exploded:
		explode()
		return
	var ratio: float = cumulative_time / duration
	var current_x = lerpf(start_position.x, end_position.x, ratio)
	var current_y = a * current_x ** 2 + b * current_x + c
	dynamite.global_position = Vector2(current_x, current_y)
	cumulative_time += delta

func explode():
	exploded = true
	dynamite.queue_free()
	explosion_collision.disabled = false
	explosion_sprite.play("explode")

# Below are generated by ChatGPT: find quadratic equation from 3 points
func find_quadratic_equation(points: Array) -> Dictionary:
	var x_coords = [points[0].x, points[1].x, points[2].x]
	var y_coords = [points[0].y, points[1].y, points[2].y]

	# Construct the coefficient matrix
	var A = [
		[x_coords[0] * x_coords[0], x_coords[0], 1],
		[x_coords[1] * x_coords[1], x_coords[1], 1],
		[x_coords[2] * x_coords[2], x_coords[2], 1]
	]

	var B = [y_coords[0], y_coords[1], y_coords[2]]

	# Solve for a, b, c using matrix inversion
	var A_inv = inverse_matrix_3x3(A)
	if A_inv == null:
		return {}

	var coefficients = multiply_matrix_vector(A_inv, B)
	return {"a": coefficients[0], "b": coefficients[1], "c": coefficients[2]}

# Helper function to compute the inverse of a 3x3 matrix
func inverse_matrix_3x3(matrix: Array):
	var det = (
		matrix[0][0] * (matrix[1][1] * matrix[2][2] - matrix[1][2] * matrix[2][1])
		- matrix[0][1] * (matrix[1][0] * matrix[2][2] - matrix[1][2] * matrix[2][0])
		+ matrix[0][2] * (matrix[1][0] * matrix[2][1] - matrix[1][1] * matrix[2][0])
	)

	if abs(det) < 1e-6:
		return null  # Singular matrix (no solution)

	var inv_det = 1.0 / det
	var adj = [
		[
			(matrix[1][1] * matrix[2][2] - matrix[1][2] * matrix[2][1]) * inv_det,
			(matrix[0][2] * matrix[2][1] - matrix[0][1] * matrix[2][2]) * inv_det,
			(matrix[0][1] * matrix[1][2] - matrix[0][2] * matrix[1][1]) * inv_det
		],
		[
			(matrix[1][2] * matrix[2][0] - matrix[1][0] * matrix[2][2]) * inv_det,
			(matrix[0][0] * matrix[2][2] - matrix[0][2] * matrix[2][0]) * inv_det,
			(matrix[0][2] * matrix[1][0] - matrix[0][0] * matrix[1][2]) * inv_det
		],
		[
			(matrix[1][0] * matrix[2][1] - matrix[1][1] * matrix[2][0]) * inv_det,
			(matrix[0][1] * matrix[2][0] - matrix[0][0] * matrix[2][1]) * inv_det,
			(matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]) * inv_det
		]
	]
	return adj

# Helper function to multiply a 3x3 matrix with a 3x1 vector
func multiply_matrix_vector(matrix: Array, vector: Array) -> Array:
	return [
		matrix[0][0] * vector[0] + matrix[0][1] * vector[1] + matrix[0][2] * vector[2],
		matrix[1][0] * vector[0] + matrix[1][1] * vector[1] + matrix[1][2] * vector[2],
		matrix[2][0] * vector[0] + matrix[2][1] * vector[1] + matrix[2][2] * vector[2]
	]


func _on_animated_sprite_2d_animation_finished() -> void:
	queue_free()


func _on_explosion_body_entered(body: Node2D) -> void:
	if "player" in body.get_groups():
		body.take_damage(DAMAGE, explosion)
